Fix some typos

diff --git a/blocks/nowplaying b/blocks/nowplaying
--- a/blocks/nowplaying
+++ b/blocks/nowplaying
@@ -1,36 +1,41 @@
 #!/bin/bash
 #DELAY=0.05
 DELAY=0
-PLAYER_LIST="DeaDBeeF,spotify,rhythmbox"
+#PLAYER_LIST="DeaDBeeF,spotify,rhythmbox"
+# automatically picks the most recently-used player
+PLAYER_LIST="playerctld"
 CHROME_ID=$(playerctl -l | grep chrome)
 
 if [[ "${CHROME_ID}" != "" ]]; then
-    PLAYERCTL="playerctl --player=${PLAYER_LIST}--ignore-player=${CHROME_ID}"
+    PLAYERCTL="playerctl --player=${PLAYER_LIST} --ignore-player=${CHROME_ID}"
 else
     PLAYERCTL="playerctl --player=${PLAYER_LIST}"
 fi
 
 print_status() {
-    pauseStatus=$(${PLAYERCTL} status 2>&1 | head -n1)
+    pauseStatus=$(${PLAYERCTL} status 2>&1 | egrep -v "^$" | head -n1)
     if [[ "${pauseStatus}" == "No players found" || "${pauseStatus}" == "No player could handle this command" || "${pauseStatus}" == "" ]]; then
-        exit 0
+        echo "Cannot find player"
+        echo "Cannot find player"
+        echo ""
+        exit 1
     fi
     if [ $? -gt 0 ]; then
-        exit 0
+        exit 1
     fi
     if [[ "${pauseStatus}" == "Stopped" ]]; then
         exit 0
     fi
     artist=$(${PLAYERCTL} metadata artist)
     title=$(${PLAYERCTL} metadata title)
-    spotifyStatus="${artist} | ${title}"
+    playerMetadata="${artist} | ${title}"
     pauseString=""
     if [[ "${pauseStatus}" == "Paused" ]]; then
         pauseString=" "
     fi
 
-    echo "${spotifyStatus}${pauseString}"
-    echo "${spotifyStatus}${pauseString}"
+    echo "${playerMetadata}${pauseString}"
+    echo "${playerMetadata}${pauseString}"
     echo ""    
 }
 
