Externalise weather API key

diff --git a/blocks/weather b/blocks/weather
--- a/blocks/weather
+++ b/blocks/weather
@@ -1,10 +1,31 @@
 #!/bin/bash
 # Based on http://openweathermap.org/current
 
-API_KEY="44db6a862fba0b067b1930da0d769e98"
+# get your own API key by registering at http://openweathermap.org 
+# put it in ~/.config/i3blocks/openweathermap_api_key as a single line:
+# OPENWEATHERMAP_API_KEY="<your key here>"
+
+# read API key from file
+KEY_FOUND=false
+if [ -f ~/.config/i3blocks/openweathermap_api_key ]; then
+    source ~/.config/i3blocks/openweathermap_api_key
+    KEY_FOUND=true
+fi
+if [[ "${OPENWEATHERMAP_API_KEY}" == "" ]]; then
+    KEY_FOUND=false
+fi
+if [[ "${KEY_FOUND}" == "false" ]]; then
+    echo "API key missing"
+    echo "API key missing"
+    echo ""
+    exit 1
+fi
 
 # Check on http://openweathermap.org/find
 CITY_ID="${BLOCK_INSTANCE}"
+if [[ "${BLOCK_INSTANCE}" == "" ]]; then
+    CITY_ID=$1
+fi
 
 URGENT_LOWER=0
 URGENT_HIGHER=30
@@ -16,37 +37,41 @@ ICON_STORM=""
 ICON_SNOW=""
 ICON_FOG=""
 
-SYMBOL_CELSIUS="℃"
+#SYMBOL_CELSIUS="℃"
+#SYMBOL_CELSIUS="℃"
+SYMBOL_CELSIUS="°c"
 
-WEATHER_URL="http://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&appid=${API_KEY}&units=metric"
+WEATHER_URL="http://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&appid=${OPENWEATHERMAP_API_KEY}&units=metric"
 
 WEATHER_INFO=$(wget -qO- "${WEATHER_URL}")
-WEATHER_MAIN=$(echo "${WEATHER_INFO}" | grep -o -e '\"main\":\"[a-Z]*\"' | awk -F ':' '{print $2}' | tr -d '"')
-WEATHER_TEMP=$(echo "${WEATHER_INFO}" | grep -o -e '\"temp\":\-\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')
+#WEATHER_MAIN=$(echo "${WEATHER_INFO}" | grep -o -e '\"main\":\"[a-Z]*\"' | awk -F ':' '{print $2}' | tr -d '"')
+#WEATHER_TEMP=$(echo "${WEATHER_INFO}" | grep -o -e '\"temp\":\-\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')
+WEATHER_MAIN=$(echo "${WEATHER_INFO}" | jq -r '.weather[].main')
+WEATHER_TEMP=$(printf "%.0f" $(echo "${WEATHER_INFO}" | jq -r '.main.temp'))
 
 if [[ "${WEATHER_MAIN}" = *Snow* ]]; then
-  echo "${ICON_SNOW} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
-  echo "${ICON_SNOW} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
+  echo "${ICON_SNOW}  ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
+  echo "${ICON_SNOW}  ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
   echo ""
 elif [[ "${WEATHER_MAIN}" = *Rain* ]] || [[ "${WEATHER_MAIN}" = *Drizzle* ]]; then
-  echo "${ICON_RAINY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
-  echo "${ICON_RAINY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
+  echo "${ICON_RAINY}  ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
+  echo "${ICON_RAINY}  ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
   echo ""
 elif [[ "${WEATHER_MAIN}" = *Cloud* ]]; then
-  echo "${ICON_CLOUDY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
-  echo "${ICON_CLOUDY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
+  echo "${ICON_CLOUDY}  ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
+  echo "${ICON_CLOUDY}  ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
   echo ""
 elif [[ "${WEATHER_MAIN}" = *Clear* ]]; then
-  echo "${ICON_SUNNY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
-  echo "${ICON_SUNNY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
+  echo "${ICON_SUNNY}  ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
+  echo "${ICON_SUNNY}  ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
   echo ""
 elif [[ "${WEATHER_MAIN}" = *Fog* ]] || [[ "${WEATHER_MAIN}" = *Mist* ]]; then
-  echo "${ICON_FOG} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
-  echo "${ICON_FOG} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
+  echo "${ICON_FOG}  ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
+  echo "${ICON_FOG}  ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
   echo ""
 else
-  echo "${WEATHER_MAIN} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
-  echo "${WEATHER_MAIN} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
+  echo "${WEATHER_MAIN}  ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
+  echo "${WEATHER_MAIN}  ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
   echo ""
 fi
 
